apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: micro
spec:
  type: LoadBalancer
  selector:
    app: be
  ports:
    - port: 80 # external port
      targetPort: 8080 # containerPort inside each pod
