apiVersion: apps/v1
kind: Deployment
metadata:
  name: be1
  namespace: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
      be: "1"
  template:
    metadata:
      labels:
        app: be
        be: "1"
    spec:
      containers:
        - name: be1
          image: rhaloubi8/be1:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MONGO_URI
              value: mongodb+srv://redahaloubi8:Reda2001@ccang.of74yrg.mongodb.net/
            - name: REDIS_URI
              value: redis://redis:6379
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
