services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M



  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  be1:
    container_name: be1
    build: 
      context: ./BE_1
      args:
        NODE_ENV: production
    ports:
      - "8081:8081"
    volumes:
      - ./BE_1:/app
    environment:
      - PORT=8081
      - MONGO_URI=mongodb+srv://redahaloubi8:Reda2001@ccang.of74yrg.mongodb.net/
      - REDIS_URI=redis://redis:6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - redis
      - kafka
  be2:
    container_name: be2
    build: 
      context: ./BE_2
      args:
        NODE_ENV: production
    ports:
      - "8082:8082"
    volumes:
      - ./BE_2:/app
    environment:
      - PORT=8082
      - MONGO_URI=mongodb+srv://redahaloubi8:Reda2001@ccang.of74yrg.mongodb.net/
      - REDIS_URI=redis://redis:6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - redis
      - kafka
