# 02‑kafka.yaml  (single‑node demo broker)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME # point at the Service
              value: kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms256M"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: micro
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
